name: cve-2018-15664
class: docker
type: container_escape
dependencies:
  - name: docker-ce
    version: 18.03.1
    versions:
      - < 18.06.1
links:
  - https://nvd.nist.gov/vuln/detail/CVE-2018-15664
  - https://seclists.org/oss-sec/2019/q2/131
