name: cve-2017-1002101
class: kubernetes
type: container_escape
dependencies:
  - name: kubectl
    version: 1.9.3
    versions: ~
  - name: kubelet
    version: 1.9.3
    versions: ~
  - name: kubeadm
    version: 1.9.3
    versions: ~

links:
  - https://nvd.nist.gov/vuln/detail/CVE-2017-1002101
  - https://makocchi.medium.com/kubernetes-cve-2017-1002101-en-5a30bf701a3e
