name: cve-2021-25741
class: kubernetes
type: container_escape
dependencies:
  - name: kubectl
    version: 1.17.1
    versions: ~
  - name: kubelet
    version: 1.17.1
    versions: ~
  - name: kubeadm
    version: 1.17.1
    versions: ~
links:
  - https://nvd.nist.gov/vuln/detail/CVE-2021-25741
  - https://seclists.org/oss-sec/2021/q3/172
  - https://github.com/kubernetes/kubernetes/issues/104980
