name: cve-2018-1002105
class: kubernetes
type: privilege_escalation
dependencies:
  - name: kubectl
    version: 1.11.1
    versions: ~
  - name: kubelet
  - name: test
    version: 1.11.1
    versions: ~
  - name: kubeadm
    version: 1.11.1
    versions: ~
links:
  - https://nvd.nist.gov/vuln/detail/CVE-2018-1002105
  - https://rancher.com/blog/2018/2018-12-04-k8s-cve/